SELECT SUM(C.SCORE) AS SCORE,
       B.EMP_NO AS EMP_NO,
       B.EMP_NAME AS EMP_NAME,
       B.POSITION AS POSITION,
       B.EMAIL AS EMAIL
FROM HR_EMPLOYEES B
INNER JOIN HR_GRADE C
ON B.EMP_NO = C.EMP_NO
GROUP BY YEAR, B.EMP_NO
HAVING C.YEAR = '2022'
ORDER BY SCORE DESC
LIMIT 1